version: "3.9"
services:
    node-app:
        restart: on-failure
        build: ./app
        ports:
            - "5000:5000"
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        depends_on: 
            - node-app